# Generated by Django 4.0.4 on 2022-05-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airtel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNo', models.CharField(max_length=12)),
                ('plans_type', models.CharField(choices=[('121 Made for you', '121 Made for you'), ('Popular', 'Popular'), ('Data', 'Data'), ('Cricket Packs', 'Cricket Packs'), ('Unlimited', 'Unlimited'), ('Combo', 'Combo'), ('Talktime', 'Talktime'), ('VAS', 'VAS')], max_length=100)),
                ('circle', models.CharField(choices=[('ALL Circle', 'ALl Circle'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar/Jharkhand', 'Bihar/Jharkhand'), ('Chennai', 'Chennai'), ('Delhi NCR', 'Delhi NCR'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himanchal Pradesh', 'Himanchal Pradesh'), ('Jammu Kashmir', 'Jammu Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Kolkata', 'Kolkata'), ('Madhya Pradesh/Chhattisgarh', 'Madhya Pradesh/Chhattisgarh'), ('Maharashtra', 'Maharashtra'), ('Mumbai', 'Mumbai'), ('North East', 'North East'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Rajashtan', 'Rajashtan'), ('Tamilnadu', 'Tamilnadu'), ('Telengana', 'Telengana'), ('UP East', 'UP East'), ('UP West', 'UP West'), ('Uttrakhand', 'Uttrakhand'), ('West Bengal', 'West Bengal')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BSNL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNo', models.CharField(max_length=12)),
                ('plans_type', models.CharField(choices=[('121 Made for you', '121 Made for you'), ('Popular', 'Popular'), ('Data', 'Data'), ('Cricket Packs', 'Cricket Packs'), ('Unlimited', 'Unlimited'), ('Combo', 'Combo'), ('Talktime', 'Talktime'), ('VAS', 'VAS')], max_length=100)),
                ('circle', models.CharField(choices=[('ALL Circle', 'ALl Circle'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar/Jharkhand', 'Bihar/Jharkhand'), ('Chennai', 'Chennai'), ('Delhi NCR', 'Delhi NCR'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himanchal Pradesh', 'Himanchal Pradesh'), ('Jammu Kashmir', 'Jammu Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Kolkata', 'Kolkata'), ('Madhya Pradesh/Chhattisgarh', 'Madhya Pradesh/Chhattisgarh'), ('Maharashtra', 'Maharashtra'), ('Mumbai', 'Mumbai'), ('North East', 'North East'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Rajashtan', 'Rajashtan'), ('Tamilnadu', 'Tamilnadu'), ('Telengana', 'Telengana'), ('UP East', 'UP East'), ('UP West', 'UP West'), ('Uttrakhand', 'Uttrakhand'), ('West Bengal', 'West Bengal')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNo', models.CharField(max_length=12)),
                ('plans_type', models.CharField(choices=[('121 Made for you', '121 Made for you'), ('Popular', 'Popular'), ('Data', 'Data'), ('Cricket Packs', 'Cricket Packs'), ('Unlimited', 'Unlimited'), ('Combo', 'Combo'), ('Talktime', 'Talktime'), ('VAS', 'VAS')], max_length=100)),
                ('circle', models.CharField(choices=[('ALL Circle', 'ALl Circle'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar/Jharkhand', 'Bihar/Jharkhand'), ('Chennai', 'Chennai'), ('Delhi NCR', 'Delhi NCR'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himanchal Pradesh', 'Himanchal Pradesh'), ('Jammu Kashmir', 'Jammu Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Kolkata', 'Kolkata'), ('Madhya Pradesh/Chhattisgarh', 'Madhya Pradesh/Chhattisgarh'), ('Maharashtra', 'Maharashtra'), ('Mumbai', 'Mumbai'), ('North East', 'North East'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Rajashtan', 'Rajashtan'), ('Tamilnadu', 'Tamilnadu'), ('Telengana', 'Telengana'), ('UP East', 'UP East'), ('UP West', 'UP West'), ('Uttrakhand', 'Uttrakhand'), ('West Bengal', 'West Bengal')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MTNL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNo', models.CharField(max_length=12)),
                ('plans_type', models.CharField(choices=[('121 Made for you', '121 Made for you'), ('Popular', 'Popular'), ('Data', 'Data'), ('Cricket Packs', 'Cricket Packs'), ('Unlimited', 'Unlimited'), ('Combo', 'Combo'), ('Talktime', 'Talktime'), ('VAS', 'VAS')], max_length=100)),
                ('circle', models.CharField(choices=[('ALL Circle', 'ALl Circle'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar/Jharkhand', 'Bihar/Jharkhand'), ('Chennai', 'Chennai'), ('Delhi NCR', 'Delhi NCR'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himanchal Pradesh', 'Himanchal Pradesh'), ('Jammu Kashmir', 'Jammu Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Kolkata', 'Kolkata'), ('Madhya Pradesh/Chhattisgarh', 'Madhya Pradesh/Chhattisgarh'), ('Maharashtra', 'Maharashtra'), ('Mumbai', 'Mumbai'), ('North East', 'North East'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Rajashtan', 'Rajashtan'), ('Tamilnadu', 'Tamilnadu'), ('Telengana', 'Telengana'), ('UP East', 'UP East'), ('UP West', 'UP West'), ('Uttrakhand', 'Uttrakhand'), ('West Bengal', 'West Bengal')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vodafone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNo', models.CharField(max_length=12)),
                ('plans_type', models.CharField(choices=[('121 Made for you', '121 Made for you'), ('Popular', 'Popular'), ('Data', 'Data'), ('Cricket Packs', 'Cricket Packs'), ('Unlimited', 'Unlimited'), ('Combo', 'Combo'), ('Talktime', 'Talktime'), ('VAS', 'VAS')], max_length=100)),
                ('circle', models.CharField(choices=[('ALL Circle', 'ALl Circle'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar/Jharkhand', 'Bihar/Jharkhand'), ('Chennai', 'Chennai'), ('Delhi NCR', 'Delhi NCR'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himanchal Pradesh', 'Himanchal Pradesh'), ('Jammu Kashmir', 'Jammu Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Kolkata', 'Kolkata'), ('Madhya Pradesh/Chhattisgarh', 'Madhya Pradesh/Chhattisgarh'), ('Maharashtra', 'Maharashtra'), ('Mumbai', 'Mumbai'), ('North East', 'North East'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Rajashtan', 'Rajashtan'), ('Tamilnadu', 'Tamilnadu'), ('Telengana', 'Telengana'), ('UP East', 'UP East'), ('UP West', 'UP West'), ('Uttrakhand', 'Uttrakhand'), ('West Bengal', 'West Bengal')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
