# Generated by Django 4.0.4 on 2022-05-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_airtel_mobileno_remove_bsnl_mobileno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airtel',
            options={'verbose_name': 'Airtel'},
        ),
    ]
