# Generated by Django 4.0.4 on 2022-05-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_airtel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airtel',
            options={},
        ),
        migrations.AlterModelTable(
            name='airtel',
            table='Airtel',
        ),
    ]
