# Generated by Django 4.0.4 on 2022-05-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_airtel_options_alter_airtel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airtel',
            options={'verbose_name': 'Airtel'},
        ),
        migrations.AlterModelOptions(
            name='bsnl',
            options={'verbose_name': 'BSNL'},
        ),
        migrations.AlterModelOptions(
            name='jio',
            options={'verbose_name': 'JIO'},
        ),
        migrations.AlterModelOptions(
            name='mtnl',
            options={'verbose_name': 'MTNL'},
        ),
        migrations.AlterModelOptions(
            name='vodafone',
            options={'verbose_name': 'Vodafone'},
        ),
        migrations.AlterModelTable(
            name='airtel',
            table=None,
        ),
    ]
