# Generated by Django 4.0.4 on 2022-05-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_airtel_options_alter_bsnl_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtel',
            name='data',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='airtel',
            name='desc',
            field=models.CharField(default='NA', max_length=300),
        ),
        migrations.AddField(
            model_name='airtel',
            name='price',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='airtel',
            name='validity',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='bsnl',
            name='data',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='bsnl',
            name='desc',
            field=models.CharField(default='NA', max_length=300),
        ),
        migrations.AddField(
            model_name='bsnl',
            name='price',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='bsnl',
            name='validity',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='jio',
            name='data',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='jio',
            name='desc',
            field=models.CharField(default='NA', max_length=300),
        ),
        migrations.AddField(
            model_name='jio',
            name='price',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='jio',
            name='validity',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='mtnl',
            name='data',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='mtnl',
            name='desc',
            field=models.CharField(default='NA', max_length=300),
        ),
        migrations.AddField(
            model_name='mtnl',
            name='price',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='mtnl',
            name='validity',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='vodafone',
            name='data',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='vodafone',
            name='desc',
            field=models.CharField(default='NA', max_length=300),
        ),
        migrations.AddField(
            model_name='vodafone',
            name='price',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='vodafone',
            name='validity',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='airtel',
            name='circle',
            field=models.CharField(choices=[('ALL Circle', 'ALl Circle'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar/Jharkhand', 'Bihar/Jharkhand'), ('Chennai', 'Chennai'), ('Delhi NCR', 'Delhi NCR'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu Kashmir', 'Jammu Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Kolkata', 'Kolkata'), ('Madhya Pradesh/Chhattisgarh', 'Madhya Pradesh/Chhattisgarh'), ('Maharashtra', 'Maharashtra'), ('Mumbai', 'Mumbai'), ('North East', 'North East'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Rajashtan', 'Rajashtan'), ('Tamilnadu', 'Tamilnadu'), ('Telengana', 'Telengana'), ('UP East', 'UP East'), ('UP West', 'UP West'), ('Uttrakhand', 'Uttrakhand'), ('West Bengal', 'West Bengal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='airtel',
            name='plans_type',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Data', 'Data'), ('Cricket Packs', 'Cricket Packs'), ('Unlimited', 'Unlimited'), ('Combo', 'Combo'), ('Talktime', 'Talktime'), ('VAS', 'VAS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bsnl',
            name='circle',
            field=models.CharField(choices=[('ALL Circle', 'ALl Circle'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar/Jharkhand', 'Bihar/Jharkhand'), ('Chennai', 'Chennai'), ('Delhi NCR', 'Delhi NCR'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu Kashmir', 'Jammu Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Kolkata', 'Kolkata'), ('Madhya Pradesh/Chhattisgarh', 'Madhya Pradesh/Chhattisgarh'), ('Maharashtra', 'Maharashtra'), ('Mumbai', 'Mumbai'), ('North East', 'North East'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Rajashtan', 'Rajashtan'), ('Tamilnadu', 'Tamilnadu'), ('Telengana', 'Telengana'), ('UP East', 'UP East'), ('UP West', 'UP West'), ('Uttrakhand', 'Uttrakhand'), ('West Bengal', 'West Bengal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bsnl',
            name='plans_type',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Data', 'Data'), ('Cricket Packs', 'Cricket Packs'), ('Unlimited', 'Unlimited'), ('Combo', 'Combo'), ('Talktime', 'Talktime'), ('VAS', 'VAS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jio',
            name='circle',
            field=models.CharField(choices=[('ALL Circle', 'ALl Circle'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar/Jharkhand', 'Bihar/Jharkhand'), ('Chennai', 'Chennai'), ('Delhi NCR', 'Delhi NCR'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu Kashmir', 'Jammu Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Kolkata', 'Kolkata'), ('Madhya Pradesh/Chhattisgarh', 'Madhya Pradesh/Chhattisgarh'), ('Maharashtra', 'Maharashtra'), ('Mumbai', 'Mumbai'), ('North East', 'North East'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Rajashtan', 'Rajashtan'), ('Tamilnadu', 'Tamilnadu'), ('Telengana', 'Telengana'), ('UP East', 'UP East'), ('UP West', 'UP West'), ('Uttrakhand', 'Uttrakhand'), ('West Bengal', 'West Bengal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jio',
            name='plans_type',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Data', 'Data'), ('Cricket Packs', 'Cricket Packs'), ('Unlimited', 'Unlimited'), ('Combo', 'Combo'), ('Talktime', 'Talktime'), ('VAS', 'VAS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mtnl',
            name='circle',
            field=models.CharField(choices=[('ALL Circle', 'ALl Circle'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar/Jharkhand', 'Bihar/Jharkhand'), ('Chennai', 'Chennai'), ('Delhi NCR', 'Delhi NCR'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu Kashmir', 'Jammu Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Kolkata', 'Kolkata'), ('Madhya Pradesh/Chhattisgarh', 'Madhya Pradesh/Chhattisgarh'), ('Maharashtra', 'Maharashtra'), ('Mumbai', 'Mumbai'), ('North East', 'North East'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Rajashtan', 'Rajashtan'), ('Tamilnadu', 'Tamilnadu'), ('Telengana', 'Telengana'), ('UP East', 'UP East'), ('UP West', 'UP West'), ('Uttrakhand', 'Uttrakhand'), ('West Bengal', 'West Bengal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mtnl',
            name='plans_type',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Data', 'Data'), ('Cricket Packs', 'Cricket Packs'), ('Unlimited', 'Unlimited'), ('Combo', 'Combo'), ('Talktime', 'Talktime'), ('VAS', 'VAS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vodafone',
            name='circle',
            field=models.CharField(choices=[('ALL Circle', 'ALl Circle'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar/Jharkhand', 'Bihar/Jharkhand'), ('Chennai', 'Chennai'), ('Delhi NCR', 'Delhi NCR'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu Kashmir', 'Jammu Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Kolkata', 'Kolkata'), ('Madhya Pradesh/Chhattisgarh', 'Madhya Pradesh/Chhattisgarh'), ('Maharashtra', 'Maharashtra'), ('Mumbai', 'Mumbai'), ('North East', 'North East'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Rajashtan', 'Rajashtan'), ('Tamilnadu', 'Tamilnadu'), ('Telengana', 'Telengana'), ('UP East', 'UP East'), ('UP West', 'UP West'), ('Uttrakhand', 'Uttrakhand'), ('West Bengal', 'West Bengal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vodafone',
            name='plans_type',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Data', 'Data'), ('Cricket Packs', 'Cricket Packs'), ('Unlimited', 'Unlimited'), ('Combo', 'Combo'), ('Talktime', 'Talktime'), ('VAS', 'VAS')], max_length=100),
        ),
    ]
