# Generated by Django 4.0.4 on 2022-05-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_airtel_data_airtel_desc_airtel_price_airtel_validity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtel',
            name='plans_type',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Unlimited', 'Unlimited'), ('Data', 'Data'), ('Cricket', 'Cricket'), ('Combo', 'Combo'), ('Talktime', 'Talktime')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bsnl',
            name='plans_type',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Unlimited', 'Unlimited'), ('Data', 'Data'), ('Cricket', 'Cricket'), ('Combo', 'Combo'), ('Talktime', 'Talktime')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jio',
            name='plans_type',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Unlimited', 'Unlimited'), ('Data', 'Data'), ('Cricket', 'Cricket'), ('Combo', 'Combo'), ('Talktime', 'Talktime')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mtnl',
            name='plans_type',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Unlimited', 'Unlimited'), ('Data', 'Data'), ('Cricket', 'Cricket'), ('Combo', 'Combo'), ('Talktime', 'Talktime')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vodafone',
            name='plans_type',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Unlimited', 'Unlimited'), ('Data', 'Data'), ('Cricket', 'Cricket'), ('Combo', 'Combo'), ('Talktime', 'Talktime')], max_length=100),
        ),
    ]
